# -*- coding: utf-8 -*-
"""`

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1unMYIAbk2OZ6Sv9bTurDupZ2nxKYM6DI
"""

`





print("Red List Columns:")
print(red.columns)

print("\nTerrestrial Columns:")
print(terrestrial.columns)

print("\nMarine Columns:")
print(marine.columns)

print("\nVulnerable Columns:")
print(vulnerable.columns)

import pandas as pd

red = pd.read_csv("red_list_index_country_timeseries.csv")
terrestrial = pd.read_csv("country_terrestrial_protected_area.csv")
marine = pd.read_csv("country_marine_protected_area.csv")
vulnerable = pd.read_csv("country_vunerable.csv")

red.head()

terrestrial.head()

marine.head()

vulnerable.head()

red.info()

terrestrial.info()

marine.info()

vulnerable.info()

terrestrial.head()

marine.head()

vulnerable.head()

print(terrestrial.columns)
print(marine.columns)
print(vulnerable.columns)

print(list(terrestrial.columns))
print(list(marine.columns))
print(list(vulnerable.columns))

print(red[['Country','Year']].head())

print(terrestrial[['Country','Year']].head())

print(marine[['Country','Year']].head())

merged = red.merge(
    terrestrial,
    on=["Country", "Year"],
    how="inner",
    suffixes=("_red", "_terrestrial")
)

merged = merged.merge(
    marine,
    on=["Country", "Year"],
    how="inner"
)

print(merged.head())
print(merged.shape)

merged.info()

merged.isnull().sum()

merged.to_csv("final_species_dataset.csv",index=False)

merged.head()

merged.shape()

merged.shape

merged.isnull().sum()

merged=merged.drop_duplicates()

merged=merged.drop_duplicates()

merged=merged.dropna(axis=1,how="all")

merged.info()

merged.to_csv("cleaned_species_dataset.csv,index=false")

print(list(merged.columns))

for col in merged.columns:
    print(col)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

marine = pd.read_csv('country_marine_protected_area.csv')
terrestrial = pd.read_csv('country_terrestrial_protected_area.csv')
vulnerable = pd.read_csv('country_vunerable.csv')
redlist = pd.read_csv('red_list_index_country_timeseries.csv')

print("All datasets loaded successfully!")

marine = pd.read_csv('/content/country_marine_protected_area.csv')
terrestrial = pd.read_csv('/content/country_terrestrial_protected_area.csv')
vulnerable = pd.read_csv('/content/country_vunerable.csv')
redlist = pd.read_csv('/content/red_list_index_country_timeseries.csv')
print("All datasets loaded successfully!")

from google.colab import files

import pandas as pd
uploaded = files.upload()

print("Marine:", marine.shape)
print("Terrestrial:", terrestrial.shape)
print("Vulnerable:", vulnerable.shape)
print("Red List:", redlist.shape)

print("===== MARINE PROTECTED AREA =====")
marine.info()

print("\n===== TERRESTRIAL PROTECTED AREA =====")
terrestrial.info()

print("\n===== VULNERABLE SPECIES =====")
vulnerable.info()

print("\n===== RED LIST INDEX =====")
redlist.info()

print("Marine columns:")
print(marine.columns.tolist())

print("\nTerrestrial columns:")
print(terrestrial.columns.tolist())

print("\nVulnerable columns:")
print(vulnerable.columns.tolist())

print("\nRed List columns:")
print(redlist.columns.tolist())

print("===== MISSING VALUES =====")

print("\nMarine:")
print(marine.isnull().sum())

print("\nTerrestrial:")
print(terrestrial.isnull().sum())

print("\nVulnerable:")
print(vulnerable.isnull().sum())

print("\nRed List:")
print(redlist.isnull().sum())

print("Marine duplicates:", marine.duplicated().sum())
print("Terrestrial duplicates:", terrestrial.duplicated().sum())
print("Vulnerable duplicates:", vulnerable.duplicated().sum())
print("Red List duplicates:", redlist.duplicated().sum())

marine_clean = marine.copy()
terrestrial_clean = terrestrial.copy()
vulnerable_clean = vulnerable.copy()
redlist_clean = redlist.copy()

print("Copies created successfully.")

marine_clean = marine_clean[
    ['COU', 'Country', 'Year', 'Value']
].copy()

marine_clean.rename(
    columns={'Value': 'Marine_Protected_Area'},
    inplace=True
)

# Terrestrial protected area
terrestrial_clean = terrestrial_clean[
    ['COU', 'Country', 'Year', 'Value']
].copy()

terrestrial_clean.rename(
    columns={'Value': 'Terrestrial_Protected_Area'},
    inplace=True
)

# Vulnerable species
vulnerable_clean = vulnerable_clean[
    ['IUCN', 'IUCN Category', 'SPEC', 'Species',
     'COU', 'Country', 'Value']
].copy()

# Red List Index
redlist_clean = redlist_clean[
    ['COU', 'Country', 'Year', 'Value']
].copy()

redlist_clean.rename(
    columns={'Value': 'Red_List_Index'},
    inplace=True
)

print("Useful columns selected.")

marine_clean = marine_clean.drop_duplicates()
terrestrial_clean = terrestrial_clean.drop_duplicates()
vulnerable_clean = vulnerable_clean.drop_duplicates()
redlist_clean = redlist_clean.drop_duplicates()

print("Duplicates removed.")
print("Marine:", marine_clean.shape)
print("Terrestrial:", terrestrial_clean.shape)
print("Vulnerable:", vulnerable_clean.shape)
print("Red List:", redlist_clean.shape)

print("Marine missing values:")
print(marine_clean.isnull().sum())

print("\nTerrestrial missing values:")
print(terrestrial_clean.isnull().sum())

print("\nVulnerable missing values:")
print(vulnerable_clean.isnull().sum())

print("\nRed List missing values:")
print(redlist_clean.isnull().sum())

marine_clean = marine.copy()
terrestrial_clean = terrestrial.copy()
vulnerable_clean = vulnerable.copy()
redlist_clean = redlist.copy()

print("Clean copies created.")

from google.colab import files
import pandas as pd

uploaded = files.upload()

marine = pd.read_csv('country_marine_protected_area.csv')
terrestrial = pd.read_csv('country_terrestrial_protected_area.csv')
vulnerable = pd.read_csv('country_vunerable.csv')
redlist = pd.read_csv('red_list_index_country_timeseries.csv')

print("All datasets loaded successfully!")

marine_clean = marine.copy()
terrestrial_clean = terrestrial.copy()
vulnerable_clean = vulnerable.copy()
redlist_clean = redlist.copy()

print("Clean copies created.")

print("MARINE COLUMNS:")
print(marine_clean.columns.tolist())

print("\nTERRESTRIAL COLUMNS:")
print(terrestrial_clean.columns.tolist())

print("\nVULNERABLE COLUMNS:")
print(vulnerable_clean.columns.tolist())

print("\nRED LIST COLUMNS:")
print(redlist_clean.columns.tolist())

print("Marine shape:", marine_clean.shape)
print("Terrestrial shape:", terrestrial_clean.shape)
print("Vulnerable shape:", vulnerable_clean.shape)
print("Red List shape:", redlist_clean.shape)

print("MARINE:")
display(marine_clean[['COU', 'Country', 'Year']].head())

print("TERRESTRIAL:")
display(terrestrial_clean[['COU', 'Country', 'Year']].head())

print("VULNERABLE:")
display(vulnerable_clean[['COU', 'Country']].head())

print("RED LIST:")
display(redlist_clean[['COU', 'Country', 'Year']].head())

print("MARINE:")
display(marine_clean[['COU', 'Country', 'Year']].head())

print("TERRESTRIAL:")
display(terrestrial_clean[['COU', 'Country', 'Year']].head())

print("VULNERABLE:")
display(vulnerable_clean[['COU', 'Country']].head())

print("RED LIST:")
display(redlist_clean[['COU', 'Country', 'Year']].head())

# Combine Marine and Terrestrial datasets
protected_area = pd.merge(
    marine_clean,
    terrestrial_clean,
    on=['COU', 'Country', 'Year'],
    how='outer',
    suffixes=('_Marine', '_Terrestrial')
)

print("Combined Protected Area Dataset:")
print(protected_area.shape)

display(protected_area.head())

combined_data = pd.merge(
    protected_area,
    redlist_clean,
    on=['COU', 'Country', 'Year'],
    how='outer'
)

print("After adding Red List dataset:")
print(combined_data.shape)

display(combined_data.head())

print("Columns in combined dataset:")
print(combined_data.columns.tolist())
print("Missing values:")
print(combined_data.isnull().sum())

print("IUCN categories:")
print(vulnerable_clean['IUCN'].value_counts())

print("\nSpecies categories:")
print(vulnerable_clean['SPEC'].value_counts().head(20))

display(
    vulnerable_clean[
        ['COU', 'Country', 'IUCN', 'SPEC', 'Species', 'Value']
    ].head(20)
)

# Make Value numeric
vulnerable_clean['Value'] = pd.to_numeric(
    vulnerable_clean['Value'],
    errors='coerce'
)

# Select the main biodiversity indicators
main_indicators = [
    'TOT_KNOWN',
    'VULNERABLE',
    'ENDANGERED',
    'CRITICAL',
    'THREATENED',
    'THREAT_PERCENT'
]

vulnerable_main = vulnerable_clean[
    vulnerable_clean['IUCN'].isin(main_indicators)
].copy()

print("Selected rows:", vulnerable_main.shape)
display(vulnerable_main.head(10))

vulnerability_country = vulnerable_main.pivot_table(
    index=['COU', 'Country'],
    columns='IUCN',
    values='Value',
    aggfunc='sum'
).reset_index()

vulnerability_country.columns.name = None

print("Country-level vulnerability data:")
print(vulnerability_country.shape)

display(vulnerability_country.head())

final_combined = pd.merge(
    combined_data,
    vulnerability_country,
    on=['COU', 'Country'],
    how='left'
)

print("FINAL COMBINED DATASET")
print(final_combined.shape)

display(final_combined.head())

print("Final columns:")
print(final_combined.columns.tolist())

print("\nMissing values:")
print(final_combined.isnull().sum())

print("Final dataset shape:", final_combined.shape)

print("\nFirst 10 rows:")
display(final_combined.head(10))

print("\nLast 10 rows:")
display(final_combined.tail(10))

print("Data types:")
print(final_combined.dtypes)

print("Total missing values:",
      final_combined.isnull().sum().sum())

print("\nMissing values by column:")
print(final_combined.isnull().sum())

final_combined.to_csv(
    'biodiversity_combined_dataset.csv',
    index=False
)

print("Combined dataset saved successfully!")

import os

print(
    "File exists:",
    os.path.exists('biodiversity_combined_dataset.csv')
)

# ==========================================
# STEP 6: EXPLORATORY DATA ANALYSIS
# ==========================================

print("Dataset Shape:")
print(final_combined.shape)

print("\nColumn Names:")
print(final_combined.columns.tolist())

print("\nStatistical Summary:")
display(final_combined.describe())

import pandas as pd

marine_clean = pd.read_csv('country_marine_protected_area.csv')
terrestrial_clean = pd.read_csv('country_terrestrial_protected_area.csv')
vulnerable_clean = pd.read_csv('country_vunerable.csv')
redlist_clean = pd.read_csv('red_list_index_country_timeseries.csv')

# Combine Marine and Terrestrial datasets
protected_area = pd.merge(
    marine_clean,
    terrestrial_clean,
    on=['COU', 'Country', 'Year'],
    how='outer',
    suffixes=('_Marine', '_Terrestrial')
)

combined_data = pd.merge(
    protected_area,
    redlist_clean,
    on=['COU', 'Country', 'Year'],
    how='outer'
)

# Make Value numeric
vulnerable_clean['Value'] = pd.to_numeric(
    vulnerable_clean['Value'],
    errors='coerce'
)

# Select the main biodiversity indicators
main_indicators = [
    'TOT_KNOWN',
    'VULNERABLE',
    'ENDANGERED',
    'CRITICAL',
    'THREATENED',
    'THREAT_PERCENT'
]

vulnerable_main = vulnerable_clean[
    vulnerable_clean['IUCN'].isin(main_indicators)
].copy()

vulnerability_country = vulnerable_main.pivot_table(
    index=['COU', 'Country'],
    columns='IUCN',
    values='Value',
    aggfunc='sum'
).reset_index()

vulnerability_country.columns.name = None

final_combined = pd.merge(
    combined_data,
    vulnerability_country,
    on=['COU', 'Country'],
    how='left'
)

# ==========================================
# STEP 6: EXPLORATORY DATA ANALYSIS
# ==========================================

print("Dataset Shape:")
print(final_combined.shape)

print("\nColumn Names:")
print(final_combined.columns.tolist())

print("\nStatistical Summary:")
display(final_combined.describe())

# Numerical columns
numeric_columns = final_combined.select_dtypes(
    include='number'
).columns.tolist()

print("Numerical columns:")
print(numeric_columns)

# Missing values
print("Missing values in each column:")
display(final_combined.isnull().sum())

import matplotlib.pyplot as plt

# Select numerical columns
numeric_data = final_combined.select_dtypes(include='number')

# Plot distributions
numeric_data.hist(
    figsize=(16, 12),
    bins=30
)

plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

correlation = numeric_data.corr()

plt.figure(figsize=(14, 10))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f"
)

plt.title("Correlation Matrix of Biodiversity Variables")
plt.show()

# Find columns related to Red List / RLI
rli_columns = [
    col for col in final_combined.columns
    if 'red' in col.lower() or 'rli' in col.lower()
]

print("Possible Red List columns:")
print(rli_columns)

# Select the RLI column automatically
rli_col = rli_columns[0]

# Make sure Year is numeric
final_combined['Year'] = pd.to_numeric(
    final_combined['Year'],
    errors='coerce'
)

final_combined[rli_col] = pd.to_numeric(
    final_combined[rli_col],
    errors='coerce'
)

# Calculate average RLI for each year
rli_trend = final_combined.groupby(
    'Year'
)[rli_col].mean().dropna()

# Plot
plt.figure(figsize=(12, 6))

plt.plot(
    rli_trend.index,
    rli_trend.values,
    marker='o'
)

plt.xlabel("Year")
plt.ylabel("Average Red List Index")
plt.title("Red List Index Trend Over Time")
plt.grid(True)

plt.show()

# Find the Red List Index column
rli_columns = [
    col for col in final_combined.columns
    if 'red' in col.lower() or 'rli' in col.lower()
]

print("Red List columns:", rli_columns)

print("RLI trend:")
display(rli_trend.to_frame(name="Average_Red_List_Index"))

# Check the relationships between the main numerical variables

print("Correlation with Red List Index:")

# Find possible RLI column
rli_columns = [
    col for col in final_combined.columns
    if 'red' in col.lower() or 'rli' in col.lower()
]

print("RLI columns:", rli_columns)

if len(rli_columns) > 0:
    rli_col = rli_columns[0]

    correlations = (
        final_combined
        .select_dtypes(include='number')
        .corr()[rli_col]
        .sort_values(ascending=False)
    )

    display(correlations.to_frame("Correlation"))

# Show the strongest positive and negative correlations

if len(rli_columns) > 0:
    print("Strongest relationships with", rli_col)
    display(
        correlations[
            correlations.index != rli_col
        ].sort_values(
            key=abs,
            ascending=False
        ).head(10).to_frame("Correlation")
    )

# ==========================================
# STEP 7: FEATURE ENGINEERING
# ==========================================

print("All numerical columns available for ML:")

numeric_columns = final_combined.select_dtypes(
    include='number'
).columns.tolist()

for col in numeric_columns:
    print("-", col)

# Check Red List-related columns again

rli_columns = [
    col for col in final_combined.columns
    if 'red' in col.lower() or 'rli' in col.lower()
]

print("\nPossible target columns:")
print(rli_columns)

print("TARGET CANDIDATES:")
print(rli_columns)

print("\nNUMERICAL FEATURES:")
for col in numeric_columns:
    print(col)

# ==========================================
# STEP 7: CREATE ML DATASET
# ==========================================

# Use the Red List Index column identified earlier
rli_col = rli_columns[0]

print("Target variable:", rli_col)

# Keep numerical columns
ml_data = final_combined.select_dtypes(include='number').copy()

# Remove rows where target is missing
ml_data = ml_data.dropna(subset=[rli_col])

print("\nML dataset shape:", ml_data.shape)

display(ml_data.head())

# Target
y = ml_data[rli_col]

# Features
X = ml_data.drop(columns=[rli_col])

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFeatures:")
print(X.columns.tolist())

print("\nTarget:")
print(y.name)

# ==========================================
# STEP 8: TRAIN / TEST SPLIT
# ==========================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("Training target:", y_train.shape)
print("Testing target:", y_test.shape)

# ==========================================
# STEP 8: TRAIN / TEST SPLIT
# ==========================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("Training target:", y_train.shape)
print("Testing target:", y_test.shape)

# ==========================================
# STEP 8: TRAIN / TEST SPLIT
# ==========================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("Training target:", y_train.shape)
print("Testing target:", y_test.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)
print("Training target:", y_train.shape)
print("Testing target:", y_test.shape)

print("final_combined shape:", final_combined.shape)

print("\nML data shape:", ml_data.shape)

print("\nX shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget column:", rli_col)

print("\nTarget missing values:")
print(y.isna().sum())

print("\nTarget non-missing values:")
print(y.notna().sum())

print("\nTarget summary:")
display(y.describe())

print("\nFirst 10 target values:")
display(y.head(10))

print("final_combined:", final_combined.shape)
print("ml_data:", ml_data.shape)
print("X:", X.shape)
print("y:", y.shape)

print("\nTarget column:", rli_col)

print("\nTarget values:")
print(y.head(10))

print("\nNon-missing target values:", y.notna().sum())

# ==========================================
# FIND THE ACTUAL RED LIST DATA
# ==========================================

red_columns = [
    col for col in final_combined.columns
    if 'red' in col.lower()
]

print("All Red List related columns:")
for col in red_columns:
    print("-", col)

print("\nNumber of Red List related columns:", len(red_columns))

# Check how many non-missing values each Red List column has

print("Non-missing values in Red List columns:\n")

for col in red_columns:
    print(
        col,
        "->",
        final_combined[col].notna().sum(),
        "non-missing values"
    )

# ==========================================
# CHECK ORIGINAL RED LIST DATASET
# ==========================================

print("Red List dataset shape:")
print(redlist.shape)

print("\nRed List columns:")
for col in redlist.columns:
    print("-", col)

print("\nFirst 5 rows:")
display(redlist.head())

print("\nNon-missing values in original Red List dataset:")

for col in redlist.columns:
    print(
        col,
        "->",
        redlist[col].notna().sum()
    )

# ==========================================
# CHECK RED LIST MERGE KEYS
# ==========================================

print("Final combined:")
print(final_combined[['Country', 'Year']].head())

print("\nOriginal Red List:")
display(redlist[['Country', 'Year', 'Variable - Red List', 'Value']].head())

print("\nData types in final_combined:")
print(final_combined[['Country', 'Year']].dtypes)

print("\nData types in redlist:")
print(redlist[['Country', 'Year']].dtypes)

# Check whether Country + Year actually match

combined_keys = set(
    zip(
        final_combined['Country'].astype(str).str.strip(),
        final_combined['Year'].astype(str).str.strip()
    )
)

redlist_keys = set(
    zip(
        redlist['Country'].astype(str).str.strip(),
        redlist['Year'].astype(str).str.strip()
    )
)

common_keys = combined_keys.intersection(redlist_keys)

print("Final combined Country-Year pairs:", len(combined_keys))
print("Red List Country-Year pairs:", len(redlist_keys))
print("Matching Country-Year pairs:", len(common_keys))

# ==========================================
# FIND RED LIST VARIABLES
# ==========================================

print("Unique Red List variables:")

display(
    redlist['Variable - Red List']
    .dropna()
    .value_counts()
    .to_frame("Count")
)

# Show examples of the Red List data

display(
    redlist[
        ['Country', 'Year', 'Variable - Red List', 'Value']
    ].head(20)
)

# ==========================================
# FIX RED LIST INDEX IN FINAL DATASET
# ==========================================

# Keep only actual Red List Index observations
rli_data = redlist[
    redlist['Variable - Red List'].astype(str).str.strip()
    == 'Red List Index'
].copy()

# Keep only the columns we need
rli_data = rli_data[
    ['Country', 'Year', 'Value']
].copy()

# Rename the numeric value
rli_data = rli_data.rename(
    columns={'Value': 'Red_List_Index'}
)

# Make sure merge keys have the same format
rli_data['Country'] = rli_data['Country'].astype(str).str.strip()
final_combined['Country'] = final_combined['Country'].astype(str).str.strip()

rli_data['Year'] = pd.to_numeric(
    rli_data['Year'],
    errors='coerce'
)

final_combined['Year'] = pd.to_numeric(
    final_combined['Year'],
    errors='coerce'
)

# Remove the old empty Red List column
if 'Variable - Red List' in final_combined.columns:
    final_combined = final_combined.drop(
        columns=['Variable - Red List']
    )

# Merge the actual RLI values
final_combined = final_combined.merge(
    rli_data,
    on=['Country', 'Year'],
    how='left'
)

print("Final dataset shape:", final_combined.shape)

print("\nRed List Index non-missing values:",
      final_combined['Red_List_Index'].notna().sum())

display(
    final_combined[
        ['Country', 'Year', 'Red_List_Index']
    ].dropna().head(10)
)

# ==========================================
# STEP 8A: CREATE ML FEATURES AND TARGET
# ==========================================

# Keep rows where Red List Index is available
ml_data = final_combined.dropna(
    subset=['Red_List_Index']
).copy()

# Select numerical columns
numeric_data = ml_data.select_dtypes(
    include='number'
).copy()

# Target
y = numeric_data['Red_List_Index']

# Features
X = numeric_data.drop(
    columns=['Red_List_Index']
)

print("ML dataset:", ml_data.shape)
print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget:", y.name)
print("\nNumber of features:", X.shape[1])

print("Missing values in X:", X.isna().sum().sum())
print("Missing values in y:", y.isna().sum())

print("\nFirst 5 target values:")
display(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)
print("Training target:", y_train.shape)
print("Testing target:", y_test.shape)

# Save the combined dataset
final_combined.to_csv(
    '/content/final_combined_dataset.csv',
    index=False
)

print("Combined dataset saved successfully!")
print("Rows:", final_combined.shape[0])
print("Columns:", final_combined.shape[1])

from google.colab import files

files.download('/content/final_combined_dataset.csv')

# ==========================================
# ML PREPARATION
# ==========================================

from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

# Keep only numerical data
ml_data = final_combined.select_dtypes(include='number').copy()

# Remove rows where the target is unavailable
ml_data = ml_data.dropna(subset=['Red_List_Index'])

# Separate features and target
X = ml_data.drop(columns=['Red_List_Index'])
y = ml_data['Red_List_Index']

# Replace infinite values
X = X.replace([float('inf'), float('-inf')], float('nan'))

# Fill missing feature values using median
imputer = SimpleImputer(strategy='median')
X = imputer.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("ML dataset:", ml_data.shape)
print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])
print("Number of features:", X_train.shape[1])

# ==========================================
# ML PREPARATION
# ==========================================

from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

# Keep only numerical data
ml_data = final_combined.select_dtypes(include='number').copy()

# Remove rows where the target is unavailable
ml_data = ml_data.dropna(subset=['Red_List_Index'])

# Separate features and target
X = ml_data.drop(columns=['Red_List_Index'])
y = ml_data['Red_List_Index']

# Replace infinite values
X = X.replace([float('inf'), float('-inf')], float('nan'))

# Fill missing feature values using median
imputer = SimpleImputer(strategy='median')
X = imputer.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("ML dataset:", ml_data.shape)
print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])
print("Number of features:", X_train.shape[1])

# ==========================================
# STEP 9: BASELINE ML MODELS
# ==========================================

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

# Create models
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(
        random_state=42
    ),
    "Random Forest": RandomForestRegressor(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    ),
    "SVR": SVR()
}

# Train models
trained_models = {}

for name, model in models.items():
    print("Training:", name)

    model.fit(X_train, y_train)

    trained_models[name] = model

print("\nAll models trained successfully!")

# ==========================================
# STEP 9B: MODEL EVALUATION
# ==========================================

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np
import pandas as pd

results = []

for name, model in trained_models.items():

    predictions = model.predict(X_test)

    mae = mean_absolute_error(
        y_test,
        predictions
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_test,
            predictions
        )
    )

    r2 = r2_score(
        y_test,
        predictions
    )

    results.append({
        "Model": name,
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2
    })

results_df = pd.DataFrame(results)

display(results_df)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.bar(
    results_df["Model"],
    results_df["R2"]
)

plt.xlabel("Model")
plt.ylabel("R² Score")
plt.title("Baseline ML Model Comparison - R² Score")
plt.xticks(rotation=20)
plt.tight_layout()
plt.show()

# Random Forest predictions
rf_model = trained_models["Random Forest"]

rf_predictions = rf_model.predict(X_test)

plt.figure(figsize=(8, 6))

plt.scatter(
    y_test,
    rf_predictions
)

plt.xlabel("Actual Red List Index")
plt.ylabel("Predicted Red List Index")
plt.title("Random Forest: Actual vs Predicted")

# Ideal prediction line
min_value = min(y_test.min(), rf_predictions.min())
max_value = max(y_test.max(), rf_predictions.max())

plt.plot(
    [min_value, max_value],
    [min_value, max_value],
    linestyle="--"
)

plt.tight_layout()
plt.show()